site_name: Impinj Gen2X APIs
site_description: Impinj Gen2X MQTT & REST API Documentation for Zebra Fixed RFID Readers
site_url: https://aa5123.github.io/-Gen2X-mqtt-api-docs/mkdocs-site/

docs_dir: mkdocs-content

theme:
  name: material
  palette:
    primary: green
    accent: green
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
  icon:
    logo: material/antenna

nav:
  - Home: index.md
  - Tutorial:
    - Overview: tutorial/overview.md
    - Setting it up: tutorial/setting-it-up.md
    - Protected Mode: tutorial/protected-mode.md
    - Tag Visibility: tutorial/tag-visibility.md
    - Short Range: tutorial/short-range.md
    - TagFocus: tutorial/tagfocus.md
    - Tag Quieting: tutorial/tag-quieting.md
    - FastID: tutorial/fastid.md
    - Get Configuration: tutorial/get-config.md
    - Start with Gen2X: tutorial/start-gen2x.md
  - API Reference: api-reference.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AA5123/-Gen2X-mqtt-api-docs

copyright: >-
  ZEBRA and the stylized Zebra head are trademarks of Zebra Technologies Corporation.
  &copy; 2024 Zebra Technologies Corporation and/or its affiliates. All rights reserved.
